name: Slack Notification on Pull Request

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
      - 1.*
      - develop
      - release*
      - MOSIP*

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test
        env:
          TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          echo ${#TEST_GITHUB_TOKEN}
          echo ${#TEST_SECRET}
          echo ${#SLACK_BOT_TOKEN}
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'U07QEJS9LM9'
          slack-message: |
            *GitHub Action Notification* :rocket:
            *Repository*: ${{ github.repository }}
            *Message*: ${{ github.event.head_commit.message || github.event.pull_request.title }}
            *Commit*: ${{ github.sha }}
            *Author*: ${{ github.event.head_commit.author.name || github.event.pull_request.user.login }}
            *Action*: ${{ github.event.action }}
            *Event Name*: ${{ github.event_name }}
            *Branch (ref)*: ${{ github.ref }}
            *Workflow*: ${{ github.workflow }}
            *PR/Commit URL*: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
