name: Build data-archive

on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - master
      - 1.*
      - develop
      - release*
      - MOSIP*

jobs:
  build-dockers:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'data-archive'
            SERVICE_NAME: 'data-archive'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: bn46/kattu/.github/workflows/docker-build.yml@develop
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEVOPS }}
      # SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }} # Optional if you want a different token for this repo
      # SLACK_MAPPING: ${{ secrets.SLACK_MAPPING }}
  notify-slack:
    needs: build-dockers  # Ensures this job runs after build-dockers
    uses: bn46/kattu/.github/workflows/slack-notification.yml@develop # Call the reusable Slack Notification workflow
    with:
      pr_author: ${{ github.event.pull_request.user.login }}  # Use the PR author if available
      repo: ${{ github.repository }}
      commit: ${{ github.sha }}
      message: ${{ github.event.head_commit.message }}  # or ${{ github.event.inputs.message }} for manual triggers
      status: ${{ job.status }}
      workflow: ${{ github.workflow }}
      job_name: ${{ github.job }}
    secrets:
      slack_mapping: ${{ secrets.SLACK_MAPPING }}  # Centralized secret
      slack_oauth_token: ${{ secrets.SLACK_OAUTH_TOKEN }}  # Centralized secret
